### ISSUE TITLE
Usolveable hidden symmetry puzzle

### ISSUE THREAD

**Issue by AlcedoAttis** [SerGreen/TheWitnessPuzzles#1]
![screenshot_2017-10-10-17-06-30-450_com sergreen thewitnesspuzzles](https://user-images.githubusercontent.com/31535277/31394472-b1392246-adde-11e7-9aea-617090ae247e.png)

This is a hidden symmetry puzzle,
And if I'm not really dumb it's unsolveable.

**Comment by SerGreen** [comment]
Yep, just found a bug where eraser rule may fail to spawn knowingly wrong rule piece, thus creating unsolvable panel. Thanks for report.
