### ISSUE TITLE
Missing rule for subtractive tetris

### ISSUE THREAD

**Issue by instr3** [SerGreen/TheWitnessPuzzles#14]
In the original game, the subtractive tetris has a special rule: if all tetris in one region can be eliminated by subtractive tetris then the shape of the region no longer matters.

Here are some examples of such puzzles:

![image](https://user-images.githubusercontent.com/13694510/103763271-8bed6d00-5054-11eb-8e53-a8a05e01fbe2.png)

The checker of this program does not consider the case. It is not a big issue since the generator seems to also ignore the case, so you can always produce correct solutions even under the missing rule.

One example is illustrated below. The solution itself is wrong (as expected), but the lower-left region should be correct (while the program thinks it is wrong).

![image](https://user-images.githubusercontent.com/13694510/103763678-2948a100-5055-11eb-9b6a-c0a586316dba.png)

A fix for the checker is easy to implement as in PR #15. The generator side seems more complex, so I did not implement this on my own.

**Comment by SerGreen** [comment]
Good find, i totally missed this. And thanks for the checker fix too. :)  

As for the panel generator: yeah, the way it generates tetris rules doesn't allow for situations like the reference panels from The Witness. I think it tries to fill the entire sector with tetris shapes if tetris rule is chosen by rng.  
In general, current panel generator isn't very good and is a mess overall. I'd like to rewrite it at some point, but that's a big undertaking.
