### ISSUE TITLE
Windows 10 says there's a dangerous trojan in The Witness Puzzles.exe

### ISSUE THREAD

**Issue by ursa202** [SerGreen/TheWitnessPuzzles#19]
First download seemed fine, but after unzip there was a warning about a serious threat, the downloaded zip-file was automatically deleted and the exe-file was put in quarantine. The identified threat according to Windows Defender is:

Trojan:Win32/Sabsik.TE.A!ml

From what I've found online, this might be a false positive, but I'm not sure how to procced with this

This happened with the latest version (1.0.10) but the previous version (1.0.9) doesn't appear to have the same issue

**Comment by SerGreen** [comment]
That's odd, the game doesn't even try to do anything hacky and 1.0.10 didn't change a lot, just writing saves to a different directory, so not sure where this alert came from.  

I just downloaded v1.0.10 release, unzipped it and checked in Windows Defender, it found nothing wrong with it. Version of malware definitions for Defender is 1.349.1234.0, the latest as of now, 2021-09-22.  

So i guess Windows Defender just had a brain fart. Try updating its definitions if it still detects a malware.

**Comment by ursa202** [comment]
Yep, appears to be just fine now, as updated Defender definitions doesn't find anything

Cheers!
