### ISSUE TITLE
Invalid puzzle solution accepted

### ISSUE THREAD

**Issue by hpp3** [SerGreen/TheWitnessPuzzles#2]
https://imgur.com/gmdMH2K
https://imgur.com/5a1sJh7

This solution was accepted as correct when it should not be valid. The top four tiles are part of the same shape which is a 2x2 square, but there is a line cutting through part of the 2x2 square.

**Comment by SerGreen** [comment]
This is actually intended. All that matters is the area itself, if there is non-enclosed line inside the area, it does not count. _If you can connect two blocks with a path, that does not cross the line, then these blocks are in the same area._  
I couldn't find similar panel in The Witness for the reference, so i decided not to handle this kind of situation differently.
