### ISSUE TITLE
Sequential Seed Generation

### ISSUE THREAD

**Issue by Leron4551** [SerGreen/TheWitnessPuzzles#20]
I'm not expecting anything since there haven't been any commits made to this repo in a long time, but I figured it wouldn't hurt to ask...

I love this app on Android, and have always been curious how many of the 999,999,999 puzzles I've actually seen. Now that I have a new phone, I'm wondering if it would be possible for @SerGreen (if you have the desire/bandwidth) or someone else (or even me if someone can explain where I need to look) to modify the puzzle generator class to simply advance the seed by 1 after a puzzle is completed?

That way I can start on the first puzzle and just work my way up over time. No idea if that requires a huge lift or if it's as simple changing a single line of code, but I figured I'd shoot my question into the aether and hope for a response.

**Comment by SerGreen** [comment]
Happy to hear you like the app. :)  

Sequential mode is an interesting idea, i like it. It wouldn't even require modification of the generator class, it can already accept seed number. There are 2 places where generation of a new (random) puzzle happens: [in the main menu when there are currently no unsolved puzzle](https://github.com/SerGreen/TheWitnessPuzzles/blob/37eb3661d51e0986a56a5967a416e13dec189546/TWP%20Shared/GameScreens/MenuGameScreen.cs#L62) and [in the puzzle screen when you click the next puzzle button](https://github.com/SerGreen/TheWitnessPuzzles/blob/37eb3661d51e0986a56a5967a416e13dec189546/TWP%20Shared/GameScreens/PanelScreen/PanelGameScreen.cs#L139). So we'd need to remember the current sequential seed globally somewhere and then pass the next number to the `GeneratePanel(seed_here)` in those 2 lines.  

I will try to implement this soon (-ish), thanks for the suggestion!

**Comment by Leron4551** [comment]
Thanks so much! and no expectations of rushing it, this is a very minor request and in the meantime I can just do more random puzzles

**Comment by SerGreen** [comment]
Kept you waiting, huh?  
https://github.com/SerGreen/TheWitnessPuzzles/releases/tag/v1.0.11

**Comment by Leron4551** [comment]
> Kept you waiting, huh? https://github.com/SerGreen/TheWitnessPuzzles/releases/tag/v1.0.11

Wow! Thank you so much. I honestly wasn't expecting it to happen before the end of the year! I really appreciate the effort.

I am having difficulty installing it though. I get an error reading: `App not installed as app isn't compatible with your phone.`

I'm using a Google Pixel 7 on Android version 13 build TD1A.221105.001

**Comment by Leron4551** [comment]
@SerGreen, after some research I suspect this is because the pixel 7 no longer supports 32-bit apps.

**Comment by SerGreen** [comment]
@Leron4551 Oh damn, really? Why, Google..?  

Ok, you must be right then, i see in project options that i only have `armeabi-v7a` selected, but not `arm64-v8a`.  
![image](https://user-images.githubusercontent.com/4000373/205568373-8c820b2f-9fdb-4f60-b5a3-d9dc7d0d4299.png)

I recompiled it selecting all available platforms, try installing either `-arm64-v8a` or `all_versions` apk, i added new files to `v1.0.11` release.

**Comment by Leron4551** [comment]
The all_versions APK worked! Blissfully stuck on puzzle 000000006 and excited to see what's next. Thanks again!

**Comment by SerGreen** [comment]
Awesome, glad it worked!
