### ISSUE TITLE
Colored squares should care about colored stars

### ISSUE THREAD

**Issue by hpp3** [SerGreen/TheWitnessPuzzles#3]
![image](https://user-images.githubusercontent.com/448866/31875763-59c5618c-b784-11e7-9b1f-943ff18662b9.png)

What happened: This solution is accepted as correct.
What is expected: This solution is invalid because the green stars and red squares are in the same partition.

Explanation: In The Witness, the squares' constraint is that they cannot exist in the same partition as any differently other colored element. This includes stars. (Note that stars do not care about other colors, so 2 red stars + 2 green stars is valid, whereas 2 green stars and 2 red squares is not).

**Comment by SerGreen** [comment]
Wrong. Here's proof from The Witness: https://imgur.com/a/SCkwL (__Treehouse solutions spoiler!__)  

Colored squares care __only__ about other colored squares, and colored stars care about anything, but __only__ if it has the same color.
