### ISSUE TITLE
Can't Swipe Up Directly From Start

### ISSUE THREAD

**Issue by Rybadour** [SerGreen/TheWitnessPuzzles#4]
In my very first puzzle I tried to go up directly from the start node but it wouldn't budge at all.
Not sure why they would be the case but one weird possibility is that the level generated two start nodes in the middle of the puzzle touching each other (one above the other).

**Comment by SerGreen** [comment]
Probably it generated the puzzle where you control two symmetrical lines at the same time, but the second line is invisible. Lines cannot pass through each other, so when you move your main line up, mirrored invisible line moves down and they collide.  
It's like a [puzzle on this screenshot](https://i.imgur.com/ERZeKJZ.png), but one line is invisible.  

You can find this kind of puzzles on the Symmetry Island in the original The Witness, it actually teaches you that the second line can be invisible.  

And, yeah, i never uploaded binaries with a fix to puzzle generator (fix is in the code, there's just no updated release), so sometimes it can generate impossible puzzles (only if eraser/elimination rule is present), so feel free to skip puzzles that you don't like/can't solve with the trash bin button.
