### ISSUE TITLE
In some rare occasions, the board can be unsolvable

### ISSUE THREAD

**Issue by instr3** [SerGreen/TheWitnessPuzzles#5]
In some rare occasions, the board can be unsolvable. I found that the problem occurs when all of the following conditions are satisfied:

(1) Eliminator is generated
(2) Eliminator is used to erase an uncovered hexagon on some nodes
(3) There is no place for the uncovered hexagon to generate

Then there will be no hexagon generated, which means the board is not guaranteed to be solvable.

Examples:
![image](https://user-images.githubusercontent.com/13694510/65396782-f901c400-dd77-11e9-89f4-e9432bad1e40.png)

![image](https://user-images.githubusercontent.com/13694510/65396763-e38c9a00-dd77-11e9-825f-28860496bfe6.png)

Special thanks to many guys in the Witness Tencent QQ group (246303424) for identifying this issue.

**Comment by instr3** [comment]
Closed by https://github.com/SerGreen/TheWitnessPuzzles/pull/7

**Comment by SerGreen** [comment]
Oh wow, great find, thank you! Honestly, i did not expect that someone would actually play it, let alone tinkering with that abomination of a code, haha.  

I never updated the apk release after fixing another unsolvable panel bug a long time ago, so probably i should go and do it at least now.

Thank you and everyone else who helped with this contribution!

**Comment by instr3** [comment]
@SerGreen Many thanks! We really appreciate your work as it is currently the only app that generates playable the witness puzzles.
